import { SiteContent } from './types';

export const enContent: SiteContent = {
  nav: {
    home: 'Home',
    about: 'About',
    faq: 'FAQ',
    contact: 'Contact',
    demo: 'Try Demo',
  },
  hero: {
    headline: 'Stories born from the place where you stand.',
    subheadline: 'PlaceEcho turns GPS/photos into a short story + audio, tailored to your language and style.',
    ctaTryDemo: 'Try Demo',
    ctaContact: 'Join Waitlist',
    bullets: {
      local: 'Local & accurate',
      multilingual: 'Multilingual',
      audio: 'Instant audio',
    },
    mockFlow: 'GPS → Story → Play Audio',
  },
  howItWorks: {
    title: 'How It Works',
    steps: [
      {
        number: 1,
        title: 'Share Location',
        description: 'Allow location access or upload a photo',
      },
      {
        number: 2,
        title: 'Place Recognition',
        description: 'System identifies place / POI via maps',
      },
      {
        number: 3,
        title: 'Story Generation',
        description: 'Story generated by your preferences (length / style / realism)',
      },
      {
        number: 4,
        title: 'Audio Creation',
        description: 'Audio version generated automatically',
      },
      {
        number: 5,
        title: 'Save & Discover',
        description: 'Story saved + discover similar stories',
      },
    ],
  },
  useCases: {
    title: 'Who Is It For?',
    cases: [
      {
        id: 'travelers',
        title: 'Travelers',
        description: 'Turn every destination into a memorable story',
        icon: 'plane',
      },
      {
        id: 'families',
        title: 'Families',
        description: 'Create magical stories during family trips',
        icon: 'users',
      },
      {
        id: 'guides',
        title: 'Tour Guides',
        description: 'Enhance tours with rich, localized narratives',
        icon: 'map',
      },
      {
        id: 'municipalities',
        title: 'Municipalities',
        description: 'Bring heritage sites to life for visitors',
        icon: 'building',
      },
      {
        id: 'museums',
        title: 'Museums',
        description: 'Audio companion for exhibitions',
        icon: 'landmark',
      },
      {
        id: 'creators',
        title: 'Creators',
        description: 'Generate story snippets for content',
        icon: 'pen',
      },
    ],
  },
  features: {
    title: 'Features',
    groups: [
      {
        title: 'Story Engine',
        features: [
          'Length: Short / Medium / Long',
          'Style: Historical / Poetic / Documentary / Personal / Adventure',
          'Language: Hebrew / English / Russian + RTL/LTR',
        ],
      },
      {
        title: 'Audio',
        features: [
          'In-app playback',
          'Replay / Resume',
          'Share links',
        ],
      },
      {
        title: 'Smart Memory',
        features: [
          '"Similar stories" via embeddings',
          'Search by place / topic',
          'Story history',
        ],
      },
    ],
  },
  gallery: {
    title: 'Story Examples',
    randomButton: 'Random Story',
    playButton: 'Play (Mock)',
    stories: [
      {
        id: '1',
        place: 'Tel Aviv Beach',
        tone: 'Poetic',
        snippet: 'Where the Mediterranean whispers secrets to the sand...',
        fullStory: "Where the Mediterranean whispers secrets to the sand, generations of dreamers have walked these shores. The salt air carries memories of fishermen who once cast their nets at dawn, and lovers who traced their names in the wet sand at dusk. Today, joggers pass by ancient footsteps, unaware they're running through history.",
      },
      {
        id: '2',
        place: 'Jerusalem Old City',
        tone: 'Historical',
        snippet: 'Three thousand years of prayers have polished these stones...',
        fullStory: 'Three thousand years of prayers have polished these stones smooth. Each cobblestone holds the weight of empires—Roman legions, Crusader knights, Ottoman merchants, and modern pilgrims all leaving invisible imprints. The walls remember what history books forget: the laughter of children, the haggling of traders, the quiet tears of the faithful.',
      },
      {
        id: '3',
        place: 'Carmel Market',
        tone: 'Personal',
        snippet: 'My grandmother always said the best spices hide in plain sight...',
        fullStory: "My grandmother always said the best spices hide in plain sight. She taught me to find them here, between the mountains of oranges and rivers of olives. The market hasn't changed much since her time—still the same beautiful chaos, vendors calling out in five languages, strangers becoming friends over shared samples.",
      },
      {
        id: '4',
        place: 'Masada Fortress',
        tone: 'Documentary',
        snippet: 'Rising 400 meters above the Dead Sea, this fortress tells a tale of defiance...',
        fullStory: "Rising 400 meters above the Dead Sea, this fortress tells a tale of defiance. King Herod built it as a refuge, complete with bathhouses and storerooms. But it's the last stand of 960 Jewish rebels against Rome in 73 CE that echoes through these ruins. Their choice—freedom in death over slavery—still resonates.",
      },
      {
        id: '5',
        place: 'Haifa Port',
        tone: 'Adventure',
        snippet: 'Every ship that enters this harbor brings a new chapter...',
        fullStory: 'Every ship that enters this harbor brings a new chapter. Pirates once lurked these waters, merchants traded silk for spices, and immigrants glimpsed their new homeland from crowded decks. The port never sleeps—cranes dance against the Carmel backdrop, loading dreams and unloading hope.',
      },
      {
        id: '6',
        place: 'Galilee Hills',
        tone: 'Poetic',
        snippet: 'Green waves frozen in time, these hills have cradled civilizations...',
        fullStory: 'Green waves frozen in time, these hills have cradled civilizations. Shepherds still walk paths worn by biblical feet. In spring, wildflowers paint the slopes in impossible colors—red anemones, purple irises, golden chamomile. The wind carries songs older than memory, newer than tomorrow.',
      },
    ],
  },
  trust: {
    title: 'Trust & Transparency',
    items: [
      {
        title: 'Privacy First',
        description: 'Location is stored only if you choose to save it.',
        icon: 'shield',
      },
      {
        title: 'Full Control',
        description: 'You can delete your history anytime.',
        icon: 'trash',
      },
      {
        title: 'Fast Generation',
        description: 'Stories generated in ~10–20 seconds.',
        icon: 'zap',
      },
    ],
  },
  finalCTA: {
    headline: 'Want early access?',
    namePlaceholder: 'Your name',
    emailPlaceholder: 'your@email.com',
    reasonPlaceholder: 'Why does this interest you?',
    submitButton: 'Join Waitlist',
    bookDemo: 'Book a Demo (B2B)',
  },
  demo: {
    title: 'Try the Demo',
    locationPlaceholder: 'Enter a location (e.g., "Tel Aviv Beach")',
    useMyLocation: 'Use My Location',
    lengthLabel: 'Story Length',
    styleLabel: 'Story Style',
    languageLabel: 'Language',
    generateButton: 'Generate Story',
    lengths: ['Short', 'Medium', 'Long'],
    styles: ['Historical', 'Poetic', 'Documentary', 'Personal', 'Adventure'],
    languages: ['English', 'Hebrew', 'Russian'],
  },
};
